name: Auto Calculate AHP TOPSIS SPKLU

on:
  schedule:
    # Mengubah ke '0 * * * *' jika ingin tepat setiap 60 menit (setiap awal jam)
    # Jika tetap '*/30 * * * *' maka berjalan setiap 30 menit
    - cron: '*/30 * * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas numpy requests

      - name: Run AHP TOPSIS Analysis
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          # UPDATE DI SINI: Menambahkan ahp_results.json agar ikut disimpan
          git add data_spklu.json 
          git add ahp_results.json
          git commit -m "Update hasil perhitungan AHP TOPSIS otomatis" || exit 0
          git push
